export enum Country {
  UNITED_STATES = "US",
  UNITED_KINGDOM = "UK",
  CANADA = "CA",
  AUSTRALIA = "AU",
  GERMANY = "DE",
  FRANCE = "FR",
  SPAIN = "ES",
  ITALY = "IT",
  JAPAN = "JP",
  CHINA = "CN",
  INDIA = "IN",
  BRAZIL = "BR",
  MEXICO = "MX",
  SOUTH_AFRICA = "ZA",
  EGYPT = "EG",
  NIGERIA = "NG",
  KENYA = "KE",
  GHANA = "GH",
  MOROCCO = "MA",
  TUNISIA = "TN"
}
