export * from './ArchiveCourseDTO'
export * from "./CreateChapterDTO";
export * from "./CreateCourseDTO";
export * from "./AddInstructorDTO";
export * from "./CreateLessonDTO";
export * from "./GetChapterLessonsDTO";
export * from "./GetCourseChaptersDTO";
export * from "./GetCoursesDTO";
export * from "./GetInstructorsDTO";
export * from './PublishCourseDTO'